language: php

dist: focal

matrix:
  include:
    - php: 7.3
      dist: xenial
    - php: 7.4
    - php: 8.0
      env: ANALYSIS='true'
    - php: nightly

  allow_failures:
    - php: nightly

before_script:
  - if [[ "$ANALYSIS" == 'true' ]]; then composer require php-coveralls/php-coveralls:^2.1.0 ; fi
  - composer install -n

script:
  - if [[ "$ANALYSIS" != 'true' ]]; then XDEBUG_MODE=coverage ./vendor/bin/phpunit; fi
  - if [[ "$ANALYSIS" == 'true' ]]; then XDEBUG_MODE=coverage ./vendor/bin/phpunit --coverage-clover clover.xml ; fi

after_success:
  - if [[ "$ANALYSIS" == 'true' ]]; then vendor/bin/php-coveralls --coverage_clover=clover.xml -v ; fi
